version: '2'

services:
  haproxy:
    image: eeacms/haproxy
    restart: always
    ports:
    - 8080:5000
    - 1936:1936
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "${TIMEZONE}"
    networks:
      - backend

  memcached:
    image: memcached:latest
    restart: always
    command:
    - "-m"
    - "1024"
    environment:
      TZ: "${TIMEZONE}"
    networks:
      - backend

  plone:
    image: "${IMAGE}"
    restart: always
    depends_on:
      - memcached
      - zeoserver
    environment:
      ZEO_ADDRESS: "zeoserver:8080"
      MEMCACHE_SERVER: "memcached:11211"
      CORS_ALLOW_ORIGIN: "*"
      CORS_ALLOW_METHODS: "GET"
      TZ: "${TIMEZONE}"
    volumes:
      - ./src/:/plone/instance/src/
      - ./config/plone/site.cfg:/plone/instance/site.cfg
      - ./config/plone/sources.cfg:/plone/instance/sources.cfg
    networks:
      - backend

  zeoserver:
    image: "${IMAGE}"
    restart: always
    container_name: zeoserver
    command: zeo
    volumes:
      - ./data/:/data/
    environment:
      TZ: "${TIMEZONE}"
    networks:
      - backend


networks:
  backend:
    name: backend

volumes:
  data:
