version: '3'

services:
  plone:
    image: "${IMAGE}"
    container_name: plone
    ports:
    - "8080:8080"
    environment:
      TZ: "${TIMEZONE}"
    command: ['fg']
    volumes:
      - ./data/:/data/
      - ./src/:/plone/instance/src/
      - ./config/plone/site.cfg:/plone/instance/site.cfg
      - ./config/plone/sources.cfg:/plone/instance/sources.cfg
    networks:
      - backend

networks:
  backend:
    name: backend

volumes:
  data:
